title: "Sof."

about: "Hello, my name is Sofia! I love data science, data engineering, cycling, and triathlon."
markdown: kramdown
url: ""
baseurl: "/jekyll-theme-milo"
disqus_short_name: disqus-demo-page

plugins: 
  - jekyll-paginate
  - jemoji
  
paginate_path: "/page:num/"

paginate: 5

main_toc:
  - title: Home
    url: ""
  - title: About
    url: "about"
  - title: Author
    url: "author"

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
